name: young_shoulders
description: "An app for parentified teens to vent, cope, reflect, and heal."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  shared_preferences: ^2.3.2
  shimmer: ^2.0.0
  lottie: ^2.7.0
  vibration: ^1.8.4
  url_launcher: ^6.2.5
  fl_chart: ^0.70.0
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  google_maps_flutter: ^2.3.0
  geolocator: ^14.0.2
  webview_flutter: ^4.13.0
  provider: ^6.0.5



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/animations/sunrise.json




